version: "3.8"
services:
  backend:
    container_name: backend
    image: "click-backend"
    ports:
      - "5000:5000"
  frontend:
    container_name: frontend
    image: "click-frontend"
    ports:
      - "3000:3000"
  redis:
    container_name: redis
    image: "redis:alpine"
