version: "3.8"
services:
  backend:
    container_name: backend
    image: "click-backend"
  frontend:
    container_name: frontend
    image: "click-frontend"
  redis:
    container_name: redis
    image: "redis:alpine"
